org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.5
enabled_platforms=fabric,forge,neoforge
parchment_version=1.21.4:2025.02.16

archives_base_name=immersivemc
mod_version=1.6.0-alpha4
maven_group=com.hammy275

fabric_loader_version=0.16.10
fabric_api_version=0.119.5+1.21.5

forge_version=1.21.5-55.0.1

neoforge_version=21.5.2-beta

mixin_extras_version=0.4.1

# Vivecraft versions
vivecraft_fabric_file_id=7129691
vivecraft_forge_file_id=7129692
vivecraft_neoforge_file_id=7129694

# Vivecraft dependency versions
javaosc_core_version=0.9
lwjgl_version=3.3.3