org.gradle.jvmargs=-Xmx4G

minecraft_version=1.19.4
enabled_platforms=fabric,forge
parchment_version=1.19.4:2023.06.26

archives_base_name=immersivemc
mod_version=1.6.0-alpha4
maven_group=com.hammy275

fabric_loader_version=0.16.1
fabric_api_version=0.78.0+1.19.4

forge_version=1.19.4-45.0.44

mixin_extras_version=0.4.1

# Vivecraft versions
vivecraft_fabric_file_id=7187429
vivecraft_forge_file_id=7187430

# Vivecraft dependency versions
javaosc_core_version=0.9
lwjgl_version=3.3.2