org.gradle.jvmargs=-Xmx4G

minecraft_version=1.19.2
enabled_platforms=fabric,forge
parchment_version=1.19.2:2022.11.27

archives_base_name=immersivemc
mod_version=1.6.0-alpha3
maven_group=com.hammy275

fabric_loader_version=0.16.1
fabric_api_version=0.59.0+1.19.2

forge_version=1.19.2-43.4.0

mixin_extras_version=0.4.1

# Vivecraft versions
vivecraft_fabric_file_id=7129651
vivecraft_forge_file_id=7129652

# Vivecraft dependency versions
javaosc_core_version=0.9
lwjgl_version=3.3.2