plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}
jar {
    manifest {
        attributes["MixinConfigs"] = "mixins.${mod_id}.json,mixins.forge.${mod_id}.json"
    }
}

minecraft {
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = true
    }

    facade = files(["immersivemc.facade.cfg"])

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            args "--mixin.config=mixins.${mod_id}.json"
            args "--mixin.config=mixins.forge.${mod_id}.json"
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')
            args '--mod', mod_id, '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    minecraft.mavenizer(it)
    maven { url = uri(layout.projectDirectory.dir('../.gradle/mavenizer/repo')) }
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven {
        url = "https://cursemaven.com"
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'

    api "curse.maven:vivecraft-667903:${vivecraft_forge_file_id}"

    compileOnly "curse.maven:inventoryprofilesnext-495267:8346095"
    compileOnly "curse.maven:libipn-679177:8346015" // Inventory Profiles Next dependency
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

javadoc {
    // Ignore .md files used for extra documentation added among code not intended for the Javadocs
    exclude "**/*.md"
}